Repository aurora-is-near/rainbow-bridge, pull requests merged in 2021-12, with the labels that each got.

#646 Upgrade to nearcore 1.23.0
  contracts/eth/nearbridge/contracts/NearDecoder.sol
  contracts/eth/nearbridge/test/NearBridge3.js
  contracts/eth/nearbridge/test/block_validators_v1_testnet.json
  near2eth/near2eth-block-relay/package.json
  utils/borsh.js
  yarn.lock
Labels: enhancement, P0

#650 NearOnEthClinet: add message for BP num limit
  contracts/eth/nearbridge/contracts/NearBridge.sol
Labels: enhancement

#648 Merge bsc branch
  .buildkite/pipeline.yml
  CODEOWNERS
  Dockerfile
  Makefile
  README.md
  cli/commands/start/helpers.js
  cli/index.js
  cli/init/eth-contracts.js
  cli/package.json
  contracts/eth/nearbridge/contracts/Ed25519.sol
  contracts/eth/nearbridge/contracts/NearBridge.sol
  contracts/eth/nearprover/contracts/NearProver.sol
  contracts/near/res/bsc_client.wasm
  contracts/near/res/bsc_prover.wasm
  contracts/near/res/eth_prover.wasm
  docker-compose.yml
  eth2near/eth2near-block-relay/eth-on-near-client.js
  eth2near/eth2near-block-relay/index.js
  eth2near/eth2near-block-relay/package.json
  near2eth/near2eth-block-relay/index.js
  near2eth/near2eth-block-relay/package.json
  near2eth/watchdog/package.json
  testing/package.json
  testing/transfer-eth-erc20/deploy-token.js
  testing/transfer-eth-erc20/from-near.js
  testing/vendor/ganache/package.json
  testing/vendor/ganache/yarn.lock
  utils/package.json
  utils/robust.js
  utils/scripts/start_ganache.sh
  yarn.lock
Labels: enhancement

#622 Migrate CI pipeline to GitHub actions
  .github/workflows/contracts-eth.yml
  .github/workflows/contracts-near.yml
  .github/workflows/tests.yml
  cli/commands/danger-deploy-myerc20.js
  contracts/near/eth-client/build.sh
  contracts/near/eth-prover/build.sh
  testing/ci/e2e_deploy_contract.sh
Labels: devops

#647 NearProver:add scripts&tests for bridge upgradability
  .gitignore
  cli/index.js
  contracts/eth/nearbridge/package.json
  contracts/eth/nearbridge/test/NearBridge.js
  contracts/eth/nearbridge/test/NearBridge2.js
  contracts/eth/nearbridge/test/NearBridge3.js
  contracts/eth/nearbridge/yarn.lock
  contracts/eth/nearprover/Makefile
  contracts/eth/nearprover/UPGRADE.md
  contracts/eth/nearprover/hardhat.config.js
  contracts/eth/nearprover/package.json
  contracts/eth/nearprover/test/NearProver.js
  contracts/eth/nearprover/utils/deploy_contracts.js
  contracts/eth/nearprover/utils/eth-ledger-signer.js
  contracts/eth/nearprover/utils/upgrade_bridge_address.js
  contracts/eth/nearprover/utils/upgrade_near_on_eth_client_admin.js
  contracts/eth/nearprover/yarn.lock
  utils/borsh.js
  yarn.lock
Labels: enhancement

#654 remove unecassary CI sources of nvm and yarn
  .buildkite/contracts-eth.yml
  .buildkite/contracts-near.yml
  testing/ci/e2e_ci_prepare_env.sh
Labels: devops

#662 fix a bug validate the epoch header using the previous validator set
  contracts/near/eth-client/src/lib.rs
  contracts/near/eth-client/src/tests.rs
Labels: bug

#663 Add legacy support for ledger and cleanup.
  contracts/eth/nearprover/Makefile
  contracts/eth/nearprover/hardhat.config.js
  contracts/eth/nearprover/package.json
  contracts/eth/nearprover/utils/upgrade_admin.js
  contracts/eth/nearprover/utils/upgrade_bridge_address.js
  contracts/eth/nearprover/utils/upgrade_near_on_eth_client_admin.js
  contracts/eth/nearprover/utils/utils.js
  contracts/eth/nearprover/yarn.lock
Labels: enhancement

#667 BSC fix tests: #666
  contracts/near/eth-client/src/tests.rs
Labels: bug, testing

#668 Upgrade admin: minor improvements
  contracts/eth/nearprover/UPGRADE.md
  contracts/eth/nearprover/utils/upgrade_admin.js
  contracts/eth/nearprover/utils/utils.js
Labels: enhancement
