Repository aurora-is-near/rainbow-bridge, pull requests merged in 2022-06, with the labels that each got.

#747 AdminControlled: use `call` pattern to send ether
  contracts/eth/nearbridge/contracts/AdminControlled.sol
Labels: enhancement, security

#752 Add watchdog quick configuration guide
  README.md
  near2eth/watchdog/README.md
Labels: docs

#750 Add Backstage metadata
  .catalog-info.yaml
  contracts/eth/nearbridge/.catalog-info.yaml
  contracts/eth/nearprover/.catalog-info.yaml
  contracts/near/eth-client/.catalog-info.yaml
  contracts/near/eth-prover/.catalog-info.yaml
Labels: devops

#754 CI: run Eth-client tests
  .github/workflows/contracts-near.yml
Labels: devops

#753 Update DAG Merkle roots
  cli/commands/update-dag-merkle-roots.js
  cli/index.js
  cli/package.json
  contracts/near/eth-client/src/data/dag_merkle_roots.json
  contracts/near/eth-client/src/lib.rs
  contracts/near/eth-client/src/tests.rs
  contracts/near/res/eth_client.wasm
  eth2near/eth2near-block-relay/dag_merkle_roots.json
  eth2near/eth2near-block-relay/eth-on-near-client.js
  eth2near/eth2near-block-relay/index.js
  yarn.lock
Labels: enhancement

#735 NEAR2Eth-Relay: Optimized Block Selection
  cli/commands/danger-submit-invalid-near-block.js
  cli/commands/start/near2eth-relay.js
  cli/index.js
  docs/development.md
  near2eth/near2eth-block-relay/index.js
  testing/ci/e2e.sh
  testing/ci/e2e_deploy_contract.sh
  testing/ci/test_challenge.sh
  testing/ci/test_ethrelay_catchup.sh
  utils/robust.js
Labels: enhancement, javascript

#758 CI: fixes for `nearcore` v1.28.
  cli/commands/start/near.js
Labels: bug, devops
