Repository aurora-is-near/rainbow-bridge, pull requests merged in 2022-08, with the labels that each got.

#768 Eth2 client: improve init & fix trusted mode
  contracts/near/eth-types/src/lib.rs
  contracts/near/eth2-client/src/lib.rs
  contracts/near/eth2-client/src/tests/unit_tests.rs
  contracts/near/eth2-client/test.sh
  contracts/near/eth2-utility/src/consensus.rs
  contracts/near/res/eth2_client.wasm
Labels: bug, enhancement, rust, eth-the-merge

#772 Eth2-to-Near-relay: minor improvements and fixes
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/eth2near-block-relay-rs/src/beacon_block_body_merkle_tree.rs
  eth2near/eth2near-block-relay-rs/src/beacon_block_header_with_execution_data.rs
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth1_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/logger.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
Labels: enhancement, relayers, rust

#774 CI: enable workflows on `the-merge` branch
  .github/workflows/contracts-eth.yml
  .github/workflows/contracts-near.yml
  .github/workflows/e2e.yml
  .github/workflows/lint.yml
Labels: devops

#775 Eth2-to-Near-relay: custom light-client updates fixes
  eth2near/contract_wrapper/src/contract_wrapper_trait.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
  eth2near/eth2near-block-relay-rs/src/relay_errors.rs
Labels: enhancement, relayers, rust, eth-the-merge

#773 Eth2OnNearClient: change lighthouse dependencies
  contracts/near/Cargo.lock
  contracts/near/eth-types/Cargo.toml
  contracts/near/eth2-client/Cargo.toml
  contracts/near/eth2-utility/Cargo.toml
  contracts/near/res/eth2_client.wasm
  contracts/near/res/eth_client.wasm
  contracts/near/res/eth_prover.wasm
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/finality-update-verify/Cargo.toml
Labels: dependencies, rust, eth-the-merge

#776 Eth2-to-Near-relay: add DAO contract interface
  eth2near/contract_wrapper/src/contract_wrapper_trait.rs
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/dao_types.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/lib.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
Labels: enhancement, relayers, rust, eth-the-merge

#778 Eth2-to-Near-relay: DAO contract interface fixes
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/dao_types.rs
Labels: bug, relayers, rust

#782 Eth2Near-Relay: reduce unnecessary requests to beacon chain in binary search of last Eth slot on NEAR
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
Labels: enhancement, relayers, rust

#779 Eth2-to-Near-relay: interaction with DAO
  eth2near/contract_wrapper/src/contract_wrapper_trait.rs
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/dao_types.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract_trait.rs
  eth2near/contract_wrapper/src/lib.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
Labels: enhancement, relayers, rust

#780 Eth2-to-Near-relay: bug fixes
  contracts/near/Cargo.lock
  contracts/near/Cargo.toml
  contracts/near/eth-types/Cargo.toml
  contracts/near/eth2-client/Cargo.toml
  contracts/near/eth2-utility/Cargo.toml
  contracts/near/eth2_hashing/Cargo.toml
  contracts/near/eth2_hashing/src/lib.rs
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/finality-update-verify/Cargo.toml
  eth2near/finality-update-verify/src/lib.rs
Labels: bug, relayers, rust

#783 Eth2-to-Near Relay: rid of `LightClientServer API` for fetching next_sync_committee in HandMadeLightClientUpdate
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/relay_errors.rs
  eth2near/finality-update-verify/Cargo.toml
Labels: enhancement, relayers, rust

#786 `eth-types`: make Eth2 dependencies optional
  contracts/near/Cargo.lock
  contracts/near/eth-client/Cargo.toml
  contracts/near/eth-prover/Cargo.toml
  contracts/near/eth-types/Cargo.toml
  contracts/near/eth-types/src/lib.rs
  contracts/near/eth-types/src/macros.rs
  contracts/near/res/eth2_client.wasm
  contracts/near/res/eth_client.wasm
  contracts/near/res/eth_prover.wasm
Labels: dependencies, rust
