Repository aurora-is-near/rainbow-bridge, pull requests merged in 2022-09, with the labels that each got.

#795 Fix `init` for NEAR contracts
  contracts/near/eth-client/src/lib.rs
  contracts/near/eth-prover/src/lib.rs
  contracts/near/eth2-client/Cargo.toml
  contracts/near/eth2-client/src/lib.rs
  contracts/near/eth2-client/src/tests/integration_tests.rs
  contracts/near/eth2-client/src/tests/unit_tests.rs
  contracts/near/eth2-client/test.sh
  contracts/near/res/eth2_client.wasm
  contracts/near/res/eth_client.wasm
  contracts/near/res/eth_prover.wasm
Labels: enhancement, rust

#787 Eth2Near-relay: improvements, add unit tests
  eth2near/contract_wrapper/Cargo.toml
  eth2near/contract_wrapper/data/.gitattributes
  eth2near/contract_wrapper/data/beacon_state_kiln_slot_1099392.json
  eth2near/contract_wrapper/data/beacon_state_kiln_slot_1099459.json
  eth2near/contract_wrapper/data/execution_block_headers_kiln_1099394-1099937.json
  eth2near/contract_wrapper/data/light_client_updates_kiln_1099394-1099937.json
  eth2near/contract_wrapper/data/next_sync_committee_kiln_period_133.json
  eth2near/contract_wrapper/data/next_sync_committee_kiln_period_134.json
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/dao_types.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/file_eth_client_contract.rs
  eth2near/contract_wrapper/src/lib.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/contract_wrapper/src/sandbox_contract_wrapper.rs
  eth2near/contract_wrapper/src/utils.rs
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/data/.gitattributes
  eth2near/eth2near-block-relay-rs/data/beacon_state_kiln_slot_812544.json
  eth2near/eth2near-block-relay-rs/data/beacon_state_kiln_slot_812637_period_99.json
  eth2near/eth2near-block-relay-rs/src/beacon_block_header_with_execution_data.rs
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/logger.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
  eth2near/eth2near-block-relay-rs/src/relay_errors.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
Labels: testing, relayers, rust

#781 Eth2Near-relay: Prometheus Metrics
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/prometheus_metrics.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
Labels: enhancement, relayers, rust

#802 Eth2-to-Near-relay: fix sending light client update
  eth2near/contract_wrapper/src/contract_wrapper_trait.rs
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/contract_wrapper/src/sandbox_contract_wrapper.rs
Labels: enhancement

#800 Eth2-to-Near-relay: improvements and bugs fixes
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/errors.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/lib.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth1_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
  eth2near/eth2near-block-relay-rs/src/near_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/relay_errors.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
Labels: bug, relayers, rust

#807 Eth2-to-Near-relay: tests fixes, add tests to CI
  .github/workflows/contracts-near.yml
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/errors.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/lib.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/contract_wrapper/src/sandbox_contract_wrapper.rs
  eth2near/contract_wrapper/src/utils.rs
  eth2near/contract_wrapper/test.sh
  eth2near/eth2near-block-relay-rs/src/eth1_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/prometheus_metrics.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
  eth2near/eth2near-block-relay-rs/test.sh
  eth2near/finality-update-verify/Cargo.lock
  eth2near/finality-update-verify/src/lib.rs
  eth2near/finality-update-verify/test.sh
Labels: enhancement, testing, relayers, rust

#808 Eth2Near crates: update `workspaces` to v0.5.0
  eth2near/contract_wrapper/Cargo.toml
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/sandbox_contract_wrapper.rs
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
Labels: enhancement, dependencies, relayers, rust

#810 Eth2-to-Near-relay & Eth2OnNearClient: Mainnet fixes
  contracts/near/eth2-client/src/lib.rs
  contracts/near/eth2-utility/src/consensus.rs
  contracts/near/res/eth2_client.wasm
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract_trait.rs
  eth2near/contract_wrapper/src/file_eth_client_contract.rs
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
Labels: enhancement, security, relayers, rust

#809 Eth2-to-Near-relay: sleep if send light client update was failed
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
Labels: bug, relayers, rust

#804 Eth2OnNearClient: optimizations and improvements
  contracts/near/eth2-client/src/lib.rs
  contracts/near/eth2-client/src/tests/unit_tests.rs
  contracts/near/res/eth2_client.wasm
Labels: enhancement

#817 Eth2-to-Near-relay: improve init of Eth2 client contract
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/light_client_snapshot_with_proof.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
Labels: enhancement, relayers, rust

#820 Eth2-to-Near-relay: don't panic on running
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
Labels: bug, relayers, rust

#824 Eth2Near-relay: add extra metrics to Prometheus
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/prometheus_metrics.rs
Labels: enhancement, relayers, rust

#829 Eth2-to-Near-relay: fix bug on relayer hanging up because of RPC result
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
Labels: bug, relayers, rust, eth-the-merge

#830 Update watchdog readme
  near2eth/watchdog/README.md
Labels: docs

#823 Eth2-to-Near-relay: remove some asserts and imrpove error handling
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
  eth2near/eth2near-block-relay-rs/src/relay_errors.rs
Labels: enhancement, relayers, rust

#818 Eth2-to-Near-relay: minor improvements, tests improvements and fixes
  .github/workflows/contracts-near.yml
  .gitignore
  eth2near/contract_wrapper/src/errors.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/lib.rs
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/config_for_tests.toml
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/.gitattributes
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/beacon_block_goerli_slot_3885632.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/beacon_header_goerli_slot_3885632.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/beacon_light_client_update_goerli_period_474.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/beacon_state_goerli_slot_3885664.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/beacon_state_goerli_slot_3885731.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/beacon_state_goerli_slot_3887616.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/beacon_state_goerli_slot_3887699.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/execution_block_headers_goerli_slots_3885697_3886176.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/light_client_updates_goerli_slots_3885697_3886176.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/next_sync_committee_goerli_period_473.json
  eth2near/eth2near-block-relay-rs/data/goerli_testdata/next_sync_committee_goerli_period_474.json
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/config_for_tests.rs
  eth2near/eth2near-block-relay-rs/src/eth1_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/prometheus_metrics.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
  eth2near/eth2near-block-relay-rs/test.sh
  eth2near/finality-update-verify/Cargo.lock
  eth2near/finality-update-verify/Cargo.toml
  eth2near/finality-update-verify/config_for_tests.toml
  eth2near/finality-update-verify/src/config_for_tests.rs
  eth2near/finality-update-verify/src/lib.rs
  eth2near/finality-update-verify/test.sh
Labels: testing, relayers, rust
