Repository aurora-is-near/rainbow-bridge, pull requests merged in 2022-01, with the labels that each got.

#678 Fix import loadash package
  near2eth/near2eth-block-relay/index.js
  utils/robust.js
Labels: enhancement

#686 BSC: minor refactoring and fixes
  contracts/near/eth-client/src/lib.rs
  contracts/near/eth-client/src/tests.rs
Labels: enhancement

#679 BSC client: remove zero block trust
  contracts/near/eth-client/src/lib.rs
Labels: enhancement

#687 CI: disable old tests prior to nearcore 1.23.0.
  contracts/eth/nearbridge/test/NearBridge.js
  contracts/eth/nearbridge/test/NearBridge2.js
Labels: testing, devops

#694 BSC: remove final epoch header
  contracts/near/eth-client/src/lib.rs
  contracts/near/eth-client/src/tests.rs
Labels: enhancement

#670 BSC: add unit tests
  contracts/near/eth-client/src/lib.rs
  contracts/near/eth-client/src/tests.rs
Labels: testing

#702 BSC: fix error `Header is already known`
  eth2near/eth2near-block-relay/index.js
Labels: bug
