Repository aurora-is-near/rainbow-bridge, pull requests merged in 2022-07, with the labels that each got.

#760 Fix: NEAR proof sharding fix.
  contracts/eth/nearprover/package.json
  contracts/eth/nearprover/test/NearProver.js
  contracts/eth/nearprover/test/proof7.json
  contracts/eth/nearprover/yarn.lock
  utils/borshify-proof.js
Labels: bug, testing

#764 Eth2OnNearClient: minor improvements, add unit tests
  .github/workflows/contracts-near.yml
  contracts/near/Cargo.lock
  contracts/near/eth-client/src/tests.rs
  contracts/near/eth2-client/Cargo.toml
  contracts/near/eth2-client/src/lib.rs
  contracts/near/eth2-client/src/tests.rs
  contracts/near/eth2-client/src/tests/integration_tests.rs
  contracts/near/eth2-client/src/tests/mod.rs
  contracts/near/eth2-client/src/tests/unit_tests.rs
  contracts/near/eth2-client/src/tests/utils.rs
  contracts/near/eth2-client/test.sh
  contracts/near/eth2-utility/src/consensus.rs
  contracts/near/res/eth2_client.wasm
  contracts/near/res/eth_client.wasm
  contracts/near/res/eth_prover.wasm
Labels: enhancement

#762 Eth2-to-Near-relay: prototype implementation
  contracts/near/eth-types/src/eth2.rs
  contracts/near/eth-types/src/macros.rs
  contracts/near/res/eth2_client.wasm
  eth2near/contract_wrapper/Cargo.toml
  eth2near/contract_wrapper/src/contract_wrapper_trait.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/lib.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/eth2near-block-relay-rs/.gitignore
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/beacon_block_body_merkle_tree.rs
  eth2near/eth2near-block-relay-rs/src/beacon_block_header_with_execution_data.rs
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth1_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth1data_proof.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/logger.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
  eth2near/finality-update-verify/Cargo.toml
  eth2near/finality-update-verify/src/lib.rs
Labels: relayers, rust, eth-the-merge
