Repository aurora-is-near/rainbow-bridge, pull requests merged in 2022-10, with the labels that each got.

#827 `contract-wrapper`: improve documentation
  eth2near/contract_wrapper/src/contract_wrapper_trait.rs
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract_trait.rs
  eth2near/contract_wrapper/src/file_eth_client_contract.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/contract_wrapper/src/sandbox_contract_wrapper.rs
Labels: docs, relayers, rust

#831 Eth2-to-Near-relay: minor code and naming improvements
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract_trait.rs
  eth2near/contract_wrapper/src/file_eth_client_contract.rs
  eth2near/contract_wrapper/src/near_contract_wrapper.rs
  eth2near/eth2near-block-relay-rs/src/beacon_block_body_merkle_tree.rs
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/config.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
  eth2near/finality-update-verify/src/lib.rs
Labels: relayers, rust

#834 Eth2Near-relay: сode simplifications
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/config_for_tests.rs
  eth2near/eth2near-block-relay-rs/src/eth1_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
Labels: enhancement, relayers, rust

#835 eth2near crates: add `rust-toolchain` files and fix dependencies conflicts
  eth2near/contract_wrapper/Cargo.lock
  eth2near/contract_wrapper/Cargo.toml
  eth2near/contract_wrapper/rust-toolchain
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/rust-toolchain
Labels: bug, rust

#828 Eth2Near-Relay: submit less blocks that remaining headers number
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract_trait.rs
  eth2near/contract_wrapper/src/file_eth_client_contract.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
Labels: enhancement, relayers, rust

#833 Eth2-to-Near-relay: remove limits for search non empty beacon block header
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
Labels: bug, relayers, rust

#832 Eth2Near-relay: fix linear search
  eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs
Labels: enhancement, relayers, rust

#837 Eth2-to-Near-relay: fix `LightClientUpdate` for new period
  eth2near/eth2near-block-relay-rs/Cargo.lock
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/beacon_rpc_client.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/execution_block_proof.rs
  eth2near/eth2near-block-relay-rs/src/hand_made_finality_light_client_update.rs
  eth2near/eth2near-block-relay-rs/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
Labels: bug, testing, relayers, rust

#838 CI: fix E2E tests
  cli/commands/start/eth2near-relay.js
  cli/commands/status.js
  cli/commands/update-dag-merkle-roots.js
  cli/init/near-contracts.js
  cli/init/near-token-factory.js
  eth2near/eth2near-block-relay/index.js
  near2eth/near2eth-block-relay/index.js
  testing/adapter/index.js
  testing/ci/e2e.sh
  testing/ci/test_ethrelay_catchup.sh
  testing/transfer-eth-erc20/deploy-token.js
  testing/transfer-eth-erc20/from-near.js
  testing/transfer-eth-erc20/to-near.js
  utils/address-watcher.js
  utils/borsh.js
  utils/helpers.js
  utils/package.json
  utils/robust.js
  utils/utils.js
  yarn.lock
Labels: bug, devops

#839 Eth2OnNearClient: verify signature period
  contracts/near/eth2-client/src/lib.rs
  contracts/near/res/eth2_client.wasm
Labels: enhancement, security, rust
