Repository aurora-is-near/rainbow-bridge, pull requests merged in 2023-04, with the labels that each got.

#884 Eth2Near-relayer: fix decoding success status
  eth2near/contract_wrapper/src/utils.rs
Labels: bug

#882 Eth2Client: improvements, refactoring
  contracts/near/Cargo.lock
  contracts/near/eth2-client/Cargo.toml
  contracts/near/eth2-client/src/data/.gitattributes
  contracts/near/eth2-client/src/data/eth2_client_v0.1.0_testnet.wasm
  contracts/near/eth2-client/src/data/goerli/execution_blocks_8661554_8663908.json
  contracts/near/eth2-client/src/data/goerli/light_client_update_period_635.json
  contracts/near/eth2-client/src/lib.rs
  contracts/near/eth2-client/src/migrate.rs
  contracts/near/eth2-client/src/tests/integration_tests.rs
  contracts/near/eth2-client/src/tests/unit_tests.rs
  contracts/near/eth2-client/src/tests/utils.rs
  contracts/near/eth2-utility/Cargo.toml
  contracts/near/eth2-utility/src/consensus.rs
  contracts/near/eth2-utility/src/types.rs
  contracts/near/res/eth2_client.wasm
  eth2near/Cargo.lock
  eth2near/contract_wrapper/Cargo.toml
  eth2near/contract_wrapper/src/dao_eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract.rs
  eth2near/contract_wrapper/src/eth_client_contract_trait.rs
  eth2near/contract_wrapper/src/file_eth_client_contract.rs
  eth2near/eth2-contract-init/Cargo.toml
  eth2near/eth2-contract-init/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/Cargo.toml
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth2near-block-relay-rs/src/last_slot_searcher.rs
  eth2near/eth2near-block-relay-rs/src/lib.rs
  eth2near/eth2near-block-relay-rs/src/main.rs
  eth2near/eth2near-block-relay-rs/src/test_utils.rs
  eth2near/eth_rpc_client/Cargo.toml
  eth2near/eth_rpc_client/src/hand_made_finality_light_client_update.rs
Labels: enhancement, dependencies

#894 Eth2Near-relayer: fix sending update for the next period
  eth2near/contract_wrapper/src/dao_contract.rs
  eth2near/eth2-contract-init/src/init_contract.rs
  eth2near/eth2near-block-relay-rs/src/eth2near_relay.rs
  eth2near/eth_rpc_client/src/beacon_rpc_client.rs
Labels: bug, relayers, rust
